// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nodhzumnsioftsftsbsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vZGh6dW1uc2lvZnRzZnRzYnNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MjM1NzIsImV4cCI6MjA3MzE5OTU3Mn0._po-LDJsDJe6GQEj2Tw_rqY3MouIZF_3nzHs3-JG_y4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});